# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, audit-2023 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install package
        run: |
          sudo apt-get -y install tree
          which tree
          tree .

      - name: Create env file
        run: echo "${{ secrets.TEST_ENV }}" > .env
        
      - name: Install dependencies
        run: yarn install
      
      - run: CI=true yarn test  # When CI environment variable is set to true eth-gas-reporter will create a 'gasReporterOutput.json' file
      
      - name: Generate gas usage report
        id: gas_report
        uses: santiac89/gas-report-action@v1.0.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Required to publish comment, if not present only the output 'parsed_gas_report' of the step will be present
          contracts: Shares,DraggableShares,AllowlistShares,AllowlistDraggableShares,RecoveryHub,Brokerbot,PaymentHub,OfferFactory,MultiSigWallet,Bond,BondBot # String of comma-separated contract names to include in the report
          report_file: './gasReporterOutput.json' # Default if not specified
